### ISSUE TITLE
linter error in pull request

### ISSUE THREAD

**Issue by devendra-alt** [Blessman-Newton/Microverse_Portfolio#10]
- Please! run and fix the stylelint linter error in your repository locally.

You can run the following cmd

1. `npm i`
2. `npx stylelint --fix "**/*.css"`

**Comment by Tarto-4** [comment]
In HTML, a <div> (short for division) is a container element that is used to group and organize other HTML elements together. It does not have any specific semantic meaning but is a widely used element for layout and styling purposes.

The main function of a <div> container is to provide a block-level container that allows you to apply styles, manipulate layout, and organize the structure of your web page. It acts as a building block for creating sections or divisions within a webpage.

Here are some common uses and functions of <div> containers:

    Grouping and organizing content: You can use <div> elements to group related elements together. For example, you can create a <div> container to group a set of paragraphs, headings, images, or any other content elements that are related or should be styled together.

    Layout and positioning: <div> containers are often used to create the overall layout structure of a webpage. By applying CSS styles to the <div> elements, you can control their size, position, and arrangement on the page. <div> containers can be nested inside each other to create complex layouts.

    Styling and applying CSS: <div> containers provide a target for applying CSS styles. You can assign a class or ID to a <div> and then define styles in CSS rules to control the appearance of the container and its contents. This allows you to create visually appealing designs and customize the presentation of your content.

    Scripting and interaction: <div> containers can be used as targets for JavaScript or other scripting languages. You can attach event handlers or manipulate the content within the <div> dynamically using scripting, allowing you to create interactive and dynamic web pages.

Overall, <div> containers provide a flexible and versatile way to structure and organize your HTML content, apply styles, and manipulate the layout and behavior of your web page.

This issues were raised by:
@Tarto-4
