### ISSUE TITLE
deployment link

### ISSUE THREAD

**Issue by Blessman-Newton** [Blessman-Newton/Microverse_Portfolio#8]
This is a link to my Portfolio
<a href="https://blessman-newton.github.io/Microverse_Portfolio/">Click here to view</a>

**Comment by adel-gu** [comment]
# Status: APPROVED 🟢 

**Hi @Blessman-Newton  👋🏼** 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media2.giphy.com/media/S6qkS0ETvel6EZat45/giphy.gif?cid=ecf05e476gyk3z83emdc9lc4j4dv9o37wnw14oxqbq6pqny6&rid=giphy.gif&ct=g)

## Highlights
- Used GitHub pages ✔️ 
- The live website is working ✔️ 
- The README file contains the link to the live demo ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
